/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup SpinnyGroup;
extern const Sifteo::AssetImage Spinny;
extern Sifteo::AssetGroup BallGroup;
extern const Sifteo::AssetImage Ball;
extern Sifteo::AssetGroup BootstrapGroup;
extern const Sifteo::AssetImage LoadingBg;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup MenuGroup;
extern const Sifteo::PinnedAssetImage MenuStripe;
extern const Sifteo::AssetImage MenuFooter;
extern const Sifteo::AssetImage MenuIconBall;
extern const Sifteo::AssetImage MenuLabelEmpty;
extern const Sifteo::AssetImage MenuIconSpinny;
extern const Sifteo::PinnedAssetImage MenuBg;
