/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage Title;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage Playfield;
extern const Sifteo::AssetImage PlayfieldE;
extern const Sifteo::AssetImage Brackets;
extern const Sifteo::AssetImage Markers;
extern const Sifteo::PinnedAssetImage Particle0;
extern const Sifteo::AssetImage PlayfieldA;
extern const Sifteo::AssetImage PlayfieldF;
extern const Sifteo::AssetImage PlayfieldW;
extern const Sifteo::PinnedAssetImage Particle0Warp;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
